-- =====================================================================
-- StockFlow (PA-06) · V1 · Creación completa del esquema PostgreSQL
-- Programación Aplicada 2026-2
-- Lo aplica Flyway al arrancar el backend (no se ejecuta a mano en DataGrip).
-- Una vez aplicada, esta migración NO se edita: los cambios van en V3, V4...
-- Crea el schema "stockflow" con 17 tablas + 1 vista (kardex).
-- Orden de creación respetando dependencias.
-- =====================================================================

CREATE SCHEMA IF NOT EXISTS stockflow;
SET search_path TO stockflow, public;

-- ---------------------------------------------------------------------
-- BLOQUE A · Identidad y parámetros
-- ---------------------------------------------------------------------

-- 1. usuario
CREATE TABLE usuario (
    usuario_id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    username         VARCHAR(60)  NOT NULL,
    email            VARCHAR(160) NOT NULL,
    password_hash    VARCHAR(255) NOT NULL,
    nombre_completo  VARCHAR(160) NOT NULL,
    activo           BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT pk_usuario PRIMARY KEY (usuario_id),
    CONSTRAINT uq_usuario_username UNIQUE (username),
    CONSTRAINT uq_usuario_email UNIQUE (email),
    CONSTRAINT ck_usuario_username_no_vacio CHECK (btrim(username) <> '')
);

-- 2. rol
CREATE TABLE rol (
    rol_id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    codigo       VARCHAR(40)  NOT NULL,
    nombre       VARCHAR(100) NOT NULL,
    descripcion  TEXT         NULL,
    activo       BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_rol PRIMARY KEY (rol_id),
    CONSTRAINT uq_rol_codigo UNIQUE (codigo),
    CONSTRAINT ck_rol_codigo CHECK (codigo IN
        ('ADMINISTRADOR','ENCARGADO_ALMACEN','SOLICITANTE','SUPERVISOR'))
);

-- 3. usuario_rol (puente N:M usuario <-> rol)
CREATE TABLE usuario_rol (
    usuario_rol_id  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    usuario_id      BIGINT      NOT NULL,
    rol_id          BIGINT      NOT NULL,
    asignado_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    activo          BOOLEAN     NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_usuario_rol PRIMARY KEY (usuario_rol_id),
    CONSTRAINT fk_usuario_rol_usuario FOREIGN KEY (usuario_id) REFERENCES usuario (usuario_id),
    CONSTRAINT fk_usuario_rol_rol     FOREIGN KEY (rol_id)     REFERENCES rol (rol_id),
    CONSTRAINT uq_usuario_rol UNIQUE (usuario_id, rol_id)
);

-- 4. parametro_sistema · RN-03 (permitir stock negativo se guarda aquí, en FALSE)
CREATE TABLE parametro_sistema (
    parametro_id  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    clave         VARCHAR(60)  NOT NULL,
    valor         VARCHAR(120) NOT NULL,
    descripcion   TEXT         NULL,
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT pk_parametro_sistema PRIMARY KEY (parametro_id),
    CONSTRAINT uq_parametro_clave UNIQUE (clave)
);

-- ---------------------------------------------------------------------
-- BLOQUE B · Catálogo (núcleo de los capítulos 01-07)
-- ---------------------------------------------------------------------

-- 5. categoria  (ENTIDAD PADRE del par 1:N)
CREATE TABLE categoria (
    categoria_id  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    codigo        VARCHAR(30)  NOT NULL,
    nombre        VARCHAR(100) NOT NULL,
    descripcion   TEXT         NULL,
    activo        BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT pk_categoria PRIMARY KEY (categoria_id),
    CONSTRAINT uq_categoria_codigo UNIQUE (codigo),
    CONSTRAINT uq_categoria_nombre UNIQUE (nombre),
    CONSTRAINT ck_categoria_codigo_no_vacio CHECK (btrim(codigo) <> '')
);

-- 6. producto  (ENTIDAD DEPENDIENTE del par 1:N) · RN-06
CREATE TABLE producto (
    producto_id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    categoria_id           BIGINT        NOT NULL,
    codigo                 VARCHAR(40)   NOT NULL,
    nombre                 VARCHAR(140)  NOT NULL,
    descripcion            TEXT          NULL,
    unidad_medida          VARCHAR(20)   NOT NULL DEFAULT 'UNIDAD',
    stock_minimo_default   INTEGER       NOT NULL DEFAULT 0,
    precio_referencial     NUMERIC(12,2) NULL,
    activo                 BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at             TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at             TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT pk_producto PRIMARY KEY (producto_id),
    CONSTRAINT fk_producto_categoria FOREIGN KEY (categoria_id) REFERENCES categoria (categoria_id),
    CONSTRAINT uq_producto_codigo UNIQUE (codigo),
    CONSTRAINT ck_producto_unidad_medida CHECK (unidad_medida IN
        ('UNIDAD','CAJA','PAQUETE','KILOGRAMO','LITRO','METRO')),
    CONSTRAINT ck_producto_stock_minimo CHECK (stock_minimo_default >= 0),
    CONSTRAINT ck_producto_precio CHECK (precio_referencial IS NULL OR precio_referencial >= 0),
    CONSTRAINT ck_producto_codigo_no_vacio CHECK (btrim(codigo) <> '')
);

-- 7. ubicacion
CREATE TABLE ubicacion (
    ubicacion_id  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    codigo        VARCHAR(30)  NOT NULL,
    nombre        VARCHAR(120) NOT NULL,
    tipo          VARCHAR(20)  NOT NULL DEFAULT 'DEPOSITO',
    direccion     VARCHAR(220) NULL,
    activo        BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT pk_ubicacion PRIMARY KEY (ubicacion_id),
    CONSTRAINT uq_ubicacion_codigo UNIQUE (codigo),
    CONSTRAINT ck_ubicacion_tipo CHECK (tipo IN ('ALMACEN_CENTRAL','DEPOSITO','PUNTO_CONSUMO'))
);

-- ---------------------------------------------------------------------
-- BLOQUE C · Existencias · RN-01, RN-03, RN-07
-- ---------------------------------------------------------------------

-- 8. stock (existencia por producto y ubicación)
CREATE TABLE stock (
    stock_id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    producto_id    BIGINT      NOT NULL,
    ubicacion_id   BIGINT      NOT NULL,
    cantidad       NUMERIC(14,3) NOT NULL DEFAULT 0,
    stock_minimo   NUMERIC(14,3) NOT NULL DEFAULT 0,
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_stock PRIMARY KEY (stock_id),
    CONSTRAINT fk_stock_producto  FOREIGN KEY (producto_id)  REFERENCES producto (producto_id),
    CONSTRAINT fk_stock_ubicacion FOREIGN KEY (ubicacion_id) REFERENCES ubicacion (ubicacion_id),
    CONSTRAINT uq_stock_producto_ubicacion UNIQUE (producto_id, ubicacion_id),
    CONSTRAINT ck_stock_no_negativo CHECK (cantidad >= 0),          -- RN-03
    CONSTRAINT ck_stock_minimo CHECK (stock_minimo >= 0)
);

-- ---------------------------------------------------------------------
-- BLOQUE D · Solicitudes internas · RN-05
-- ---------------------------------------------------------------------

-- 9. solicitud
CREATE TABLE solicitud (
    solicitud_id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    codigo                VARCHAR(30)  NOT NULL,
    solicitante_id        BIGINT       NOT NULL,
    ubicacion_destino_id  BIGINT       NOT NULL,
    estado                VARCHAR(20)  NOT NULL DEFAULT 'BORRADOR',
    justificacion         TEXT         NULL,
    enviada_at            TIMESTAMPTZ  NULL,
    cerrada_at            TIMESTAMPTZ  NULL,
    created_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT pk_solicitud PRIMARY KEY (solicitud_id),
    CONSTRAINT fk_solicitud_solicitante FOREIGN KEY (solicitante_id) REFERENCES usuario (usuario_id),
    CONSTRAINT fk_solicitud_ubicacion FOREIGN KEY (ubicacion_destino_id) REFERENCES ubicacion (ubicacion_id),
    CONSTRAINT uq_solicitud_codigo UNIQUE (codigo),
    CONSTRAINT ck_solicitud_estado CHECK (estado IN
        ('BORRADOR','ENVIADA','APROBADA','RECHAZADA','ATENDIDA','CANCELADA')),
    CONSTRAINT ck_solicitud_enviada CHECK (estado = 'BORRADOR' OR enviada_at IS NOT NULL)
);

-- 10. item_solicitud
CREATE TABLE item_solicitud (
    item_solicitud_id    BIGINT GENERATED BY DEFAULT AS IDENTITY,
    solicitud_id         BIGINT        NOT NULL,
    producto_id          BIGINT        NOT NULL,
    cantidad_solicitada  NUMERIC(14,3) NOT NULL,
    cantidad_atendida    NUMERIC(14,3) NOT NULL DEFAULT 0,
    CONSTRAINT pk_item_solicitud PRIMARY KEY (item_solicitud_id),
    CONSTRAINT fk_item_solicitud_solicitud FOREIGN KEY (solicitud_id) REFERENCES solicitud (solicitud_id),
    CONSTRAINT fk_item_solicitud_producto  FOREIGN KEY (producto_id)  REFERENCES producto (producto_id),
    CONSTRAINT uq_item_solicitud UNIQUE (solicitud_id, producto_id),
    CONSTRAINT ck_item_cantidad_positiva CHECK (cantidad_solicitada > 0),
    CONSTRAINT ck_item_atendida CHECK (cantidad_atendida >= 0
        AND cantidad_atendida <= cantidad_solicitada)
);

-- 11. aprobacion (1:0..1 con solicitud)
CREATE TABLE aprobacion (
    aprobacion_id  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    solicitud_id   BIGINT      NOT NULL,
    supervisor_id  BIGINT      NOT NULL,
    decision       VARCHAR(20) NOT NULL,
    comentario     TEXT        NULL,
    decidido_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_aprobacion PRIMARY KEY (aprobacion_id),
    CONSTRAINT fk_aprobacion_solicitud  FOREIGN KEY (solicitud_id)  REFERENCES solicitud (solicitud_id),
    CONSTRAINT fk_aprobacion_supervisor FOREIGN KEY (supervisor_id) REFERENCES usuario (usuario_id),
    CONSTRAINT uq_aprobacion_solicitud UNIQUE (solicitud_id),
    CONSTRAINT ck_aprobacion_decision CHECK (decision IN ('APROBADA','RECHAZADA')),
    CONSTRAINT ck_aprobacion_comentario CHECK (decision <> 'RECHAZADA' OR comentario IS NOT NULL)
);

-- ---------------------------------------------------------------------
-- BLOQUE E · Transferencias · RN-04
-- ---------------------------------------------------------------------

-- 12. transferencia
CREATE TABLE transferencia (
    transferencia_id     BIGINT GENERATED BY DEFAULT AS IDENTITY,
    codigo               VARCHAR(30) NOT NULL,
    ubicacion_origen_id  BIGINT      NOT NULL,
    ubicacion_destino_id BIGINT      NOT NULL,
    estado               VARCHAR(20) NOT NULL DEFAULT 'BORRADOR',
    motivo               TEXT        NULL,
    created_by           BIGINT      NOT NULL,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    confirmada_at        TIMESTAMPTZ NULL,
    CONSTRAINT pk_transferencia PRIMARY KEY (transferencia_id),
    CONSTRAINT fk_transferencia_origen  FOREIGN KEY (ubicacion_origen_id)  REFERENCES ubicacion (ubicacion_id),
    CONSTRAINT fk_transferencia_destino FOREIGN KEY (ubicacion_destino_id) REFERENCES ubicacion (ubicacion_id),
    CONSTRAINT fk_transferencia_usuario FOREIGN KEY (created_by) REFERENCES usuario (usuario_id),
    CONSTRAINT uq_transferencia_codigo UNIQUE (codigo),
    CONSTRAINT ck_transferencia_estado CHECK (estado IN ('BORRADOR','CONFIRMADA','ANULADA')),
    CONSTRAINT ck_transferencia_ubicaciones CHECK (ubicacion_origen_id <> ubicacion_destino_id)
);

-- 13. transferencia_detalle
CREATE TABLE transferencia_detalle (
    transferencia_detalle_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    transferencia_id         BIGINT        NOT NULL,
    producto_id              BIGINT        NOT NULL,
    cantidad                 NUMERIC(14,3) NOT NULL,
    CONSTRAINT pk_transferencia_detalle PRIMARY KEY (transferencia_detalle_id),
    CONSTRAINT fk_transferencia_detalle_transferencia FOREIGN KEY (transferencia_id)
        REFERENCES transferencia (transferencia_id),
    CONSTRAINT fk_transferencia_detalle_producto FOREIGN KEY (producto_id)
        REFERENCES producto (producto_id),
    CONSTRAINT uq_transferencia_detalle UNIQUE (transferencia_id, producto_id),
    CONSTRAINT ck_transferencia_detalle_cantidad CHECK (cantidad > 0)
);

-- ---------------------------------------------------------------------
-- BLOQUE F · Movimientos (única forma de cambiar el stock) · RN-01, RN-02
-- ---------------------------------------------------------------------

-- 14. movimiento_inventario
CREATE TABLE movimiento_inventario (
    movimiento_id     BIGINT GENERATED BY DEFAULT AS IDENTITY,
    producto_id       BIGINT        NOT NULL,
    ubicacion_id      BIGINT        NOT NULL,
    tipo              VARCHAR(25)   NOT NULL,
    cantidad          NUMERIC(14,3) NOT NULL,
    saldo_resultante  NUMERIC(14,3) NOT NULL,
    usuario_id        BIGINT        NOT NULL,
    referencia_tipo   VARCHAR(20)   NOT NULL DEFAULT 'MANUAL',
    solicitud_id      BIGINT        NULL,
    transferencia_id  BIGINT        NULL,
    motivo            VARCHAR(200)  NULL,
    ocurrido_at       TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT pk_movimiento_inventario PRIMARY KEY (movimiento_id),
    CONSTRAINT fk_movimiento_producto  FOREIGN KEY (producto_id)  REFERENCES producto (producto_id),
    CONSTRAINT fk_movimiento_ubicacion FOREIGN KEY (ubicacion_id) REFERENCES ubicacion (ubicacion_id),
    CONSTRAINT fk_movimiento_usuario   FOREIGN KEY (usuario_id)   REFERENCES usuario (usuario_id),
    CONSTRAINT fk_movimiento_solicitud FOREIGN KEY (solicitud_id) REFERENCES solicitud (solicitud_id),
    CONSTRAINT fk_movimiento_transferencia FOREIGN KEY (transferencia_id)
        REFERENCES transferencia (transferencia_id),
    CONSTRAINT ck_movimiento_tipo CHECK (tipo IN
        ('ENTRADA','SALIDA','AJUSTE_POSITIVO','AJUSTE_NEGATIVO',
         'TRANSFERENCIA_SALIDA','TRANSFERENCIA_ENTRADA')),
    CONSTRAINT ck_movimiento_cantidad CHECK (cantidad > 0),          -- RN-02
    CONSTRAINT ck_movimiento_saldo CHECK (saldo_resultante >= 0),    -- RN-03
    CONSTRAINT ck_movimiento_referencia CHECK (referencia_tipo IN
        ('MANUAL','SOLICITUD','TRANSFERENCIA','AJUSTE')),
    CONSTRAINT ck_movimiento_ref_solicitud CHECK
        (referencia_tipo <> 'SOLICITUD' OR solicitud_id IS NOT NULL),
    CONSTRAINT ck_movimiento_ref_transferencia CHECK
        (referencia_tipo <> 'TRANSFERENCIA' OR transferencia_id IS NOT NULL)
);

-- ---------------------------------------------------------------------
-- BLOQUE G · Alertas y trazabilidad · RN-07
-- ---------------------------------------------------------------------

-- 15. alerta_stock
CREATE TABLE alerta_stock (
    alerta_id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    producto_id         BIGINT        NOT NULL,
    ubicacion_id        BIGINT        NOT NULL,
    cantidad_detectada  NUMERIC(14,3) NOT NULL,
    stock_minimo        NUMERIC(14,3) NOT NULL,
    estado              VARCHAR(20)   NOT NULL DEFAULT 'ABIERTA',
    generada_at         TIMESTAMPTZ   NOT NULL DEFAULT now(),
    resuelta_at         TIMESTAMPTZ   NULL,
    CONSTRAINT pk_alerta_stock PRIMARY KEY (alerta_id),
    CONSTRAINT fk_alerta_producto  FOREIGN KEY (producto_id)  REFERENCES producto (producto_id),
    CONSTRAINT fk_alerta_ubicacion FOREIGN KEY (ubicacion_id) REFERENCES ubicacion (ubicacion_id),
    CONSTRAINT ck_alerta_estado CHECK (estado IN ('ABIERTA','RESUELTA')),
    CONSTRAINT ck_alerta_resuelta CHECK (estado <> 'RESUELTA' OR resuelta_at IS NOT NULL),
    CONSTRAINT ck_alerta_cantidades CHECK (cantidad_detectada >= 0 AND stock_minimo >= 0)
);

-- 16. historial_estado_solicitud · RN-05 (traza de transiciones)
CREATE TABLE historial_estado_solicitud (
    historial_id     BIGINT GENERATED BY DEFAULT AS IDENTITY,
    solicitud_id     BIGINT      NOT NULL,
    estado_anterior  VARCHAR(20) NULL,
    estado_nuevo     VARCHAR(20) NOT NULL,
    motivo           VARCHAR(200) NULL,
    cambiado_por     BIGINT      NOT NULL,
    cambiado_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_historial_estado_solicitud PRIMARY KEY (historial_id),
    CONSTRAINT fk_historial_solicitud FOREIGN KEY (solicitud_id) REFERENCES solicitud (solicitud_id),
    CONSTRAINT fk_historial_usuario   FOREIGN KEY (cambiado_por) REFERENCES usuario (usuario_id),
    CONSTRAINT ck_historial_estado_nuevo CHECK (estado_nuevo IN
        ('BORRADOR','ENVIADA','APROBADA','RECHAZADA','ATENDIDA','CANCELADA')),
    CONSTRAINT ck_historial_estado_anterior CHECK (estado_anterior IS NULL OR estado_anterior IN
        ('BORRADOR','ENVIADA','APROBADA','RECHAZADA','ATENDIDA','CANCELADA'))
);

-- 17. auditoria
CREATE TABLE auditoria (
    auditoria_id  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    usuario_id    BIGINT      NULL,
    entidad       VARCHAR(60) NOT NULL,
    entidad_id    BIGINT      NULL,
    accion        VARCHAR(40) NOT NULL,
    detalle       JSONB       NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_auditoria PRIMARY KEY (auditoria_id),
    CONSTRAINT fk_auditoria_usuario FOREIGN KEY (usuario_id) REFERENCES usuario (usuario_id)
);

-- ---------------------------------------------------------------------
-- RN-01 / RN-10 operativo: el movimiento y la auditoría no se borran
-- ---------------------------------------------------------------------
CREATE OR REPLACE FUNCTION fn_impedir_borrado_historico()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'Los registros de % no se pueden eliminar (trazabilidad)', TG_TABLE_NAME;
END;
$$;

CREATE TRIGGER trg_movimiento_no_delete
    BEFORE DELETE ON movimiento_inventario
    FOR EACH ROW EXECUTE FUNCTION fn_impedir_borrado_historico();

CREATE TRIGGER trg_auditoria_no_delete
    BEFORE DELETE ON auditoria
    FOR EACH ROW EXECUTE FUNCTION fn_impedir_borrado_historico();

CREATE TRIGGER trg_historial_solicitud_no_delete
    BEFORE DELETE ON historial_estado_solicitud
    FOR EACH ROW EXECUTE FUNCTION fn_impedir_borrado_historico();

-- ---------------------------------------------------------------------
-- RF-19 · Kardex: vista derivada de los movimientos (no se guarda dos veces)
-- ---------------------------------------------------------------------
CREATE VIEW vw_kardex AS
SELECT m.movimiento_id,
       m.ocurrido_at,
       p.codigo        AS codigo_producto,
       p.nombre        AS producto,
       ub.codigo       AS ubicacion,
       m.tipo,
       CASE WHEN m.tipo IN ('ENTRADA','AJUSTE_POSITIVO','TRANSFERENCIA_ENTRADA')
            THEN m.cantidad ELSE 0 END AS entrada,
       CASE WHEN m.tipo IN ('SALIDA','AJUSTE_NEGATIVO','TRANSFERENCIA_SALIDA')
            THEN m.cantidad ELSE 0 END AS salida,
       m.saldo_resultante,
       m.referencia_tipo,
       us.username     AS registrado_por,
       m.motivo
FROM movimiento_inventario m
JOIN producto p   ON p.producto_id = m.producto_id
JOIN ubicacion ub ON ub.ubicacion_id = m.ubicacion_id
JOIN usuario us   ON us.usuario_id = m.usuario_id;

-- ---------------------------------------------------------------------
-- Índices justificados
-- ---------------------------------------------------------------------
CREATE INDEX idx_producto_categoria        ON producto (categoria_id);       -- listar productos por categoría (Cap. 07)
CREATE INDEX idx_producto_nombre           ON producto (lower(nombre));      -- RF-02 búsqueda
CREATE INDEX idx_stock_ubicacion           ON stock (ubicacion_id);
CREATE INDEX idx_stock_bajo                ON stock (producto_id) WHERE cantidad <= stock_minimo; -- RF-20
CREATE INDEX idx_movimiento_producto_fecha ON movimiento_inventario (producto_id, ocurrido_at);   -- RF-19 kardex
CREATE INDEX idx_movimiento_ubicacion      ON movimiento_inventario (ubicacion_id);
CREATE INDEX idx_solicitud_estado          ON solicitud (estado);            -- RF-18 bandeja de aprobación
CREATE INDEX idx_solicitud_solicitante     ON solicitud (solicitante_id);
CREATE INDEX idx_item_solicitud_producto   ON item_solicitud (producto_id);
CREATE INDEX idx_alerta_estado             ON alerta_stock (estado, producto_id);
CREATE INDEX idx_auditoria_entidad         ON auditoria (entidad, entidad_id);

-- Verificación: ver datagrip/03_verificacion_y_pruebas.sql (sección 2, debe listar 17 tablas)
